### ISSUE TITLE
Call a simpleChildWindow from VM

### ISSUE THREAD

**Issue by leovictor** [punker76/MahApps.Metro.SimpleChildWindow#22]
Hi,

are you planning to allow call a childWindow from a ViewModel?

Thanks!

**Comment by rdoubleui** [comment]
You can do that by toggling the `IsOpen` property as shown in the [samples](https://github.com/punker76/MahApps.Metro.SimpleChildWindow#usage).

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable](https://github.com/punker76/MahApps.Metro.SimpleChildWindow/releases) or pre-release version and please use the [issue template](https://github.com/punker76/MahApps.Metro.SimpleChildWindow/issues/new).

Thank you! 🙏
