### ISSUE TITLE
how can i check if the window is opened inside c#

### ISSUE THREAD

**Issue by ivicii** [punker76/MahApps.Metro.SimpleChildWindow#71]
Hello,

how can i check if the childwindow is opened inside c#?

thanks a lot!

**Comment by Symbai** [comment]
By doing the same this extension does:

```
var metroDialogContainer = window.Template.FindName("PART_MetroActiveDialogContainer", window) as Grid;
metroDialogContainer = metroDialogContainer ?? window.Template.FindName("PART_MetroInactiveDialogsContainer", window) as Grid;
if (metroDialogContainer.Children.Contains(your window)
{
	//do something
}
```

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable](https://github.com/punker76/MahApps.Metro.SimpleChildWindow/releases) or pre-release version and please use the [issue template](https://github.com/punker76/MahApps.Metro.SimpleChildWindow/issues/new).

Thank you! 🙏
